name: Build NVDA

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        # Add commands to install dependencies here

    - name: Build NVDA
      run: |
        # Add build commands here

    - name: Save artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nvda-artifact
        path: path/to/compiled/nvda
