name: Build NVDA

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install wxPython-4.2.2a1-cp311-cp311-win32.whl
        python -m pip install -U wxpython
        pip install -r requirements.txt

    - name: Build NVDA
      run: |
        python build.py build

    - name: Save nvda.exe
      uses: actions/upload-artifact@v2
      with:
        name: nvda-exe
        path: output/nvda.exe
